### ISSUE TITLE
ثبت عنوان تکراری برای محصولات

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_backend#104]
میتوان محصولاتی با عنوان های تکراری ایجاد کرد

**Comment by likecodingloveproblems** [comment]
به دلیل ماهیت مارکت پلیسی سایت و اینکه ما کاتالوگ جامعی از محصولات نداریم لذا حجره های مختلف می توانند محصولات تکراری داشته باشند اما در یک حجره نباید محصولات تکراری باشد.
مثال: حجره الف محصول <پفک نمکی> و حجره ب محصول <پفک نمکی> را دارد.
اما حجره الف نمی تواند دو عدد محصول <پفک نمکی> با عنوان یکسان داشته باشد.

آیا موافقید ؟ @MaryamSamareh

**Comment by PouryaMansouri** [comment]
I will check it tomarrow.

**Comment by MaryamSamareh** [comment]
@

> به دلیل ماهیت مارکت پلیسی سایت و اینکه ما کاتالوگ جامعی از محصولات نداریم لذا حجره های مختلف می توانند محصولات تکراری داشته باشند اما در یک حجره نباید محصولات تکراری باشد. مثال: حجره الف محصول <پفک نمکی> و حجره ب محصول <پفک نمکی> را دارد. اما حجره الف نمی تواند دو عدد محصول <پفک نمکی> با عنوان یکسان داشته باشد.
> 
> آیا موافقید ؟ @MaryamSamareh

بله کاملا
و  دلیل گزارش این باگ هم همین بود که میتوانستیم در یک حجره دو محصول با عنوان تکراری ایجاد کنیم

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
We can solve this problem with add :
`unique_together = ('FK_Shop', 'Title')`
in product meta class, but we can't migrate it because we have dirty data in the database.
What is your opinion?

**Comment by likecodingloveproblems** [comment]
unique_together is not suitable as docs said may be deprecated...
so I use constraints, UniqueConstraints
It needs data migration as I do it these days many times
