### ISSUE TITLE
حذف محصولات از سبد خرید و تغییر ارور

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_backend#105]
زمانی که حجره محدودیت ارسال داشته باشد و شهر انتخابی در واحدهای ارسال آن نباشد، محصولات از سبد خرید حذف می شوند اما بهتر است که محصولات حذف نشوند.
ارور هم به "هیچ واحد ارسالی برای محصولات حجره ... برای نشانی شما یافت نشد. لطفا با نشانی دیگری تلاش کنید"

**Comment by likecodingloveproblems** [comment]
please prioritize @MaryamSamareh

**Comment by MaryamSamareh** [comment]
> please prioritize @MaryamSamareh

done

**Comment by likecodingloveproblems** [comment]
we need to have a WIP limit for each developer in each priority @saman7799

**Comment by PouryaMansouri** [comment]
@milad7212 @sahar-shafiee 
please check the new error style in this branch and if it is OK I will merge it to develop.
The app will raise and stop for each product if it can not find the logistic.

**Comment by sahar-shafiee** [comment]
![Capture](https://user-images.githubusercontent.com/52815608/170852795-44c6a632-46df-482f-867f-45cbfce68d3a.JPG)
@PouryaMansouri @MaryamSamareh 
به نظرم متن پیام هنوز گنگ و تک محصول اسم برده نشه بهتر 
بلکه اسم حجره نوشته شود

**Comment by PouryaMansouri** [comment]
@sahar-shafiee 
میشه لطفا الان تست کنید

**Comment by PouryaMansouri** [comment]
> ![Capture](https://user-images.githubusercontent.com/52815608/170852795-44c6a632-46df-482f-867f-45cbfce68d3a.JPG) @PouryaMansouri @MaryamSamareh به نظرم متن پیام هنوز گنگ و تک محصول اسم برده نشه بهتر بلکه اسم حجره نوشته شود

@sahar-shafiee 
لطفا چک کنید ببینید الان نمایش خطا مناسب هست یا نه

**Comment by sahar-shafiee** [comment]
@PouryaMansouri 
اگر نوشته شود محصول {نام محصول} به شهر شما ارسال نمی شود

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri اگر نوشته شود محصول {نام محصول} به شهر شما ارسال نمی شود به نظر من بهتر است

@sahar-shafiee 
من اسم حجره رو هم اضافه کردم به متن شما . چک کنید لطفا

**Comment by sahar-shafiee** [comment]
@PouryaMansouri از نظر من که مشکلی نداره خیلی ممنون از شما
