### ISSUE TITLE
error api products list

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#106]
![Capture](https://user-images.githubusercontent.com/52815608/169752602-45a5eaf0-ea5e-490d-a067-b891de707145.JPG)
ای پی ای صفحه لیست محصولات به من ارور 500 می دهد و من روی برنچ مین هستم در بک
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
You should change the address field in the Profile model too.

**Comment by likecodingloveproblems** [comment]
Ok, I'll do it

**Comment by likecodingloveproblems** [comment]
But this error is because of serializer!

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee please check this branch
