### ISSUE TITLE
تغییر شماره حجره دار

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#113]
یکی از حجره داران درخواست تغییر شماره خود را دارد ایا امکان این مسئله وجود دارد؟
@likecodingloveproblems @MaryamSamareh

**Comment by MaryamSamareh** [comment]
در این مورد بهتر است مدیریت با توجه به ویژگی های محصول و سیاست ها و قوانین اعمال شده تصمیم بگیرند و من ترجیحا نظری نمی دهم.
@sahar-shafiee

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee تیم عملیات با صلاح دید خودشون میتونن تغییر بدن فقط ی مساله ای وجود داره اونم اینه که باید User.username و Profile.MobileNumber رو با هم تغییر بدن
