### ISSUE TITLE
postman 500- landing page most sold shops

### ISSUE THREAD

**Issue by PouryaMansouri** [nakhll-company/nakhll_backend#129]
error 500

**Comment by PouryaMansouri** [comment]
Do you use this API:

{{host}}/api/v1/landing/most-sold-shops/

@milad7212 @sahar-shafiee

**Comment by milad7212** [comment]
@PouryaMansouri  قبلا برای ردیف بیشترین فروش در صفحه لندینگ سایت استفاده میکردیم که با عوض شدنش  دیگه استفاده نمیکنیم .ولی بنظرم در اینده نزدیک دوباره بگند به لندینگ اضافه کنیم

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri قبلا برای ردیف بیشترین فروش در صفحه لندینگ سایت استفاده میکردیم که با عوض شدنش دیگه استفاده نمیکنیم .ولی بنظرم در اینده نزدیک دوباره بگند به لندینگ اضافه کنیم

thanks a lot
