### ISSUE TITLE
postman error 500 - Order History List

### ISSUE THREAD

**Issue by PouryaMansouri** [nakhll-company/nakhll_backend#132]

**Comment by PouryaMansouri** [comment]
API:  {{host}}/api/v1/profile/orders/

@milad7212 @sahar-shafiee 
Did you use this API anywhere in your app?

**Comment by milad7212** [comment]
من داخل پروژه جایی ندیدم ازش استفاده شده باشه

**Comment by PouryaMansouri** [comment]
> من داخل پروژه جایی ندیدم ازش استفاده شده باشه

Thanks
