### ISSUE TITLE
نادرست بودن فرمت تاریخ تولد در صفحه پروفایل

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#147]
![169973158-28f3555b-f541-42de-9b7c-2c94f8f74f54](https://user-images.githubusercontent.com/52815608/170922765-ecfa010f-54c7-48fa-bd5f-612c87edb2b9.JPG)
![169973154-5ebca010-0197-4501-9394-4c56bd269908](https://user-images.githubusercontent.com/52815608/170922768-0cb8f598-e2e1-4728-9021-05dc7eda15aa.JPG)

**Comment by PouryaMansouri** [comment]
@sahar-shafiee 
The problem solved,
@likecodingloveproblems  please review.
