### ISSUE TITLE
api create shop error 500

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#148]
@PouryaMansouri 
ای پی ای ایجاد حجره روی برنچ main
در لوکال ارور می دهد
  | http://localhost:8000/api/v1/shop/create/
![Capture](https://user-images.githubusercontent.com/52815608/170933632-4b2b6a4d-2fa7-4e47-983e-fe3f72ae4f79.JPG)

**Comment by PouryaMansouri** [comment]
@sahar-shafiee 
Please check this API in the developer branch.

**Comment by sahar-shafiee** [comment]
@PouryaMansouri 
![Capture](https://user-images.githubusercontent.com/52815608/170945890-ea0dbb07-6543-4b13-ae6c-84ee9582fae3.JPG)

چرا خطای 400 میده؟

**Comment by PouryaMansouri** [comment]
@sahar-shafiee 
you send string for state and ...? 
you should send the state's ID.

**Comment by sahar-shafiee** [comment]
![Capture](https://user-images.githubusercontent.com/52815608/171105862-f3d23411-ec73-4dc8-812c-b0396f10f89e.JPG)
![1](https://user-images.githubusercontent.com/52815608/171105866-81386e91-9723-4f85-a217-b5717eee07f5.JPG)
@PouryaMansouri 
داده های ارسالی  مانند عکس هستند ولی با این حال خطای 400 داده میشه
روی برنچ develope

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee please send object not int

**Comment by sahar-shafiee** [comment]
@likecodingloveproblems 
![Capture](https://user-images.githubusercontent.com/52815608/172098748-8c4d7c17-1705-402d-95cf-c20585051602.JPG)
داده های ارسالی به این شکل هستند ولی ارور دریافت میکنیم
