### ISSUE TITLE
ادرس عکس پروفایل 400 می باشد

### ISSUE THREAD

**Issue by milad7212** [nakhll-company/nakhll_backend#156]
در ای پی ای
/api/v1/profile/me/
آدرس عکس پروفالی ارور 400 میدهد و در فرانت نمیتوان عکس پروفایل را نمایش داد .ای پی ای به درستی کار میکند اما ادرس عکس پروفایل وجود ندارد

**Comment by likecodingloveproblems** [comment]
لینک نمونه ای دارید ثبت کنید؟

**Comment by milad7212** [comment]
الان زمانی که عکس را اپدیت میکنیم .ای پی ای ارور 500 میده

**Comment by likecodingloveproblems** [comment]
#194 از اونجایی که خانم شفیعی این ایشو رو ایجاد کرده من ایشو رو می بندم.

> الان زمانی که عکس را اپدیت میکنیم .ای پی ای ارور 500 میده

**Comment by likecodingloveproblems** [comment]
@milad7212
