### ISSUE TITLE
error trob api

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#157]
![IMG-20220601-WA0011](https://user-images.githubusercontent.com/52815608/171380829-37c66329-3971-41b6-9c3b-b759f71bb648.jpg)
ای پی ای ترب خطا می دهد به بچه های مارکتینگ 
عکسی که بچه های مارکتینگ فرستاده اند ضمیمه شده است
لطفا بررسی نمایید
@PouryaMansouri

**Comment by sahar-shafiee** [comment]
[https://nakhll.com/shop/آن-کافی/product/دان-قهوه-60-عربیکا-آن-250-گرمی/]
تیم مارکتینگ پس از ویرایش یک محصول در سایت متوجه شده اند 
که آن محصول در ترب ویرایش نشده است
پس از ثبت تیکت در ترب گفته شده که سایت چنین اروری برمیگرداند که عکس آن در بالا موجود است
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
@sahar-shafiee 
چطوری داخل torob محصول رو قرار میدن؟‌ که من یک محصول دیگه رو خودم بزارم و چک کنم

**Comment by sahar-shafiee** [comment]
@PouryaMansouri من در این زمینه اطلاعی ندارم
اما فکر کنم اقای محسن حسنی یا اقای یوسفیان بتوانند کمکتون کنند
@saman7799

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri من در این زمینه اطلاعی ندارم اما فکر کنم اقای محسن حسنی یا اقای یوسفیان بتوانند کمکتون کنند @saman7799

احتمال داره مشکل در پروسه گذاشتن محصول باشه.

@saman7799 
چطوری محصول در ترب قرار میگیره؟

**Comment by PouryaMansouri** [comment]
torob api:
Post : {{host}}/torob/products/

It is OK

**Comment by PouryaMansouri** [comment]
@sahar-shafiee @likecodingloveproblems 
The API that we have in Postman for Torob works correctly.

@likecodingloveproblems we have two URLs for Torib in the app. Do you have any doc about Torob? 
I cant find anything on the Internet.

**Comment by sahar-shafiee** [comment]
@PouryaMansouri @likecodingloveproblems 
https://nakhll.com/shop/آن-کافی/product/دان-قهوه-60-عربیکا-آن-250-گرمی/
محصولی که بعد از ویرایش ارور داده این محصول هست

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee @PouryaMansouri hopefully this PR #179  will solve it

**Comment by sahar-shafiee** [comment]
@PouryaMansouri بی زحمت هر وقت ریو شد به من اطلاع دهید که من به بچه های مارکتینگ اطلاع دهم
