### ISSUE TITLE
دسترسی برای تغییر هزینه همه ی واحدهای ارسال

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#165]
تیم عملیات نیاز به دسترسی برای تغییر هزینه همه ی واحدهای ارسال حجره دارد

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee انجام شد فقط پوریا باید ریویو کنه 
@PouryaMansouri

**Comment by sahar-shafiee** [comment]
@PouryaMansouri بی زحمت ریو شد به من نیز اطلاع دهید
