### ISSUE TITLE
ویرایش محصول حجره بازار پسته

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#173]
محصولات حجره بازار پسته بعد از ویرایش تغییر نمی کنند

**Comment by likecodingloveproblems** [comment]
اگه امکان داره ای پی آی که کال میشه رو بفرمایید چی هست؟  @sahar-shafiee

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri pls take a look

**Comment by sahar-shafiee** [comment]
@likecodingloveproblems 
https://nakhll.com/api/v1/shop/%D8%A7%D8%B7%D9%84%D8%B3/products/e6259886-5454-4eae-9449-05985d34b164/
ای پی ای ویرایش محصول

**Comment by likecodingloveproblems** [comment]
چک کردم و مساله رو نتونستم پیدا کنم.
با خانم شفیعی مطرح شد تا مساله دقیق تر بررسی بشه. @sahar-shafiee

**Comment by sahar-shafiee** [comment]
@likecodingloveproblems توسط تیم عملیات بررسی شد و مسئله برطرف شده
