### ISSUE TITLE
ای پی ای شماره شبا

### ISSUE THREAD

**Issue by milad7212** [nakhll-company/nakhll_backend#175]
/api/v1/shop/mamaneila/settings/
قبلا این امکان وجود داشت که تنها شماره شبا با اسم صاحب حساب را اپدیت کنیم ولی الان  خطای نبود شهر و شهرستان و استان رو میگیره. لطفا بررسی بفرمایید.  چون  الان امکان ثبت شماره شبا  نیست

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri pls take a look.

**Comment by likecodingloveproblems** [comment]
قبلا این مقادیر اختیاری بودند. اگه می خواهید می تونیم دوباره اختیاری شون کنیم. @sahar-shafiee @milad7212

**Comment by sahar-shafiee** [comment]
@likecodingloveproblems @milad7212 فکر میکنم اگر دوباره اختیاری شوند بهتر چون در این صفحه دیتای شهر و استان حجره دار دریافت نمیشه
البته امکان ارسال این دیتاها وجود دارد

**Comment by likecodingloveproblems** [comment]
> @likecodingloveproblems @milad7212 فکر میکنم اگر دوباره اختیاری شوند بهتر چون در این صفحه دیتای شهر و استان حجره دار دریافت نمیشه البته امکان ارسال این دیتاها وجود دارد

خب آیا ای پی آی settings/bank-account/ استفاده می شود؟ یا settings کلی ؟

**Comment by sahar-shafiee** [comment]
@likecodingloveproblems برای ویرایش شماره شبا از این ای پی ای استفاده می شود
http://localhost:8000/api/v1/shop/%D8%A7%D8%B7%D9%84%D8%B3/settings/

**Comment by likecodingloveproblems** [comment]
@mohsenone we have an API that does anything.
