### ISSUE TITLE
خطای ای پی ای پروفایل

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#194]
در ای پی ای پروفایل اگر بخواهیم به تنهایی عکس پروفایل را اپدیت کنیم با خطا مواجه میشویم
حتما باید تاریخ تولد و جنسیت نیز وارد شوند
http://localhost:8000/api/v1/profile/edit_me/

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee متدی که کال میکنید چی هست؟

**Comment by sahar-shafiee** [comment]
@likecodingloveproblems 

  | PATCH

**Comment by PouryaMansouri** [comment]
I just update the image and I
@sahar-shafiee 

{
  "first_name": "محسن",
  "last_name": "حسنی راوری",
  "State": "222222",
  "BigCity": "6666",
  "City": "CITY_CODE",
  "Bio": "",
  "day": "01",
  "month": "01",
  "year": "1370",
  "Image": "data:image/png;base64,iV....
  "FK_User": {
    "first_name": "محسن",
    "last_name": "حسنی راوری"
  },
  "BrithDay": "1370-01-01"
}

**Comment by likecodingloveproblems** [comment]
@milad7212

**Comment by milad7212** [comment]
![Uploading localhost_3007_profile_ (4).png…]()
بررسی که کردم به درستی کار میکنه و اپدیت میشود .فقط ادرسی که ذخیره میشه برای عکس و برمیگردونه ای پی ای ادرسش 404 هست
@likecodingloveproblems 
@PouryaMansouri

**Comment by sahar-shafiee** [comment]
@PouryaMansouri @likecodingloveproblems 
در صورتی که کاربر بخواهد فقط عکس رو ویرایش کند باید کدام ها متغییرها ارسال شوند؟

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri @likecodingloveproblems در صورتی که کاربر بخواهد فقط عکس رو ویرایش کند باید کدام ها متغییرها ارسال شوند؟

@sahar-shafiee 
مشکل رو من پیدا کردم و برطرف کردم.

**Comment by PouryaMansouri** [comment]
@milad7212 
چون آدرس لود عکس ها برای سرور اصلی هست در لوکال خطا میگیری مگر نه درسته همه چی

**Comment by milad7212** [comment]
@PouryaMansouri 
نه ادرس عکس 404 هست. شما ای پی ای رو که میگیرید .ادرسش رو داخل مرورگر میزنید ادرس صفحه 404 هست

**Comment by PouryaMansouri** [comment]
> 

خب درسته. عکس رو توی لوکال ذخیره میکنه ولی داره آدرس سرور نخل رو موقع فراخوانی بهت میده
و چون این عکس روی سرور نیست شما خطا میگیری

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri نه ادرس عکس 404 هست. شما ای پی ای رو که میگیرید .ادرسش رو داخل مرورگر میزنید ادرس صفحه 404 هست

@milad7212 

خب درسته. عکس رو توی لوکال ذخیره میکنه ولی داره آدرس سرور نخل رو موقع فراخوانی بهت میده
و چون این عکس روی سرور نیست شما خطا میگیری

**Comment by milad7212** [comment]
@PouryaMansouri 
من روی سرور اصلی یک تست میکنم نتیجشو بهتون میگم
