### ISSUE TITLE
products that has parent category

### ISSUE THREAD

**Issue by likecodingloveproblems** [nakhll-company/nakhll_backend#195]
products must have categories that are on the leaves, to have the maximum specifications and details.

**Comment by likecodingloveproblems** [comment]
I extract categories that are parent and have related products
[category_has_products_is_not_leaf.csv](https://github.com/nakhll-company/nakhll_backend/files/8883442/category_has_products_is_not_leaf.csv)

**Comment by likecodingloveproblems** [comment]
products of those categories
[product_with_category_has_products_is_not_leaf.csv](https://github.com/nakhll-company/nakhll_backend/files/8883449/product_with_category_has_products_is_not_leaf.csv)


محصولات کتگوری هایی که فرزند دارند.

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh این تسک کاملا وابسته است به اینکه دسته بندی ها رو شاید بخواهیم از اول باز طراحی کنیم.

**Comment by MaryamSamareh** [comment]
> @MaryamSamareh این تسک کاملا وابسته است به اینکه دسته بندی ها رو شاید بخواهیم از اول باز طراحی کنیم.

با اجتمال زیادی این اتفاق خواهد افتاد و دسته بندی ها تغییر می کنند. به همین من فعلا این ایشو را می بندم تا اگر تصمیم درمورد تغییر دسته بندی ها عوض شد یا این اتفاق نیفتاد دوباره این تسک را ایجاد می کنیم.
