### ISSUE TITLE
خطای پنل جگو

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#199]
روندی که با ارور در پنل جنگو مواجه می شوند =>  از  پنل کاربری => به لیست حجره ها وقتی روی یکی از حجره ها کلیک میکنیم و وارد صفحه اون حجره شدیم بالا سمت چپ یدونه کلید هست که نوشته شده مشاهده در وبگاه ۵- روی اون که کلیک میکنیم با صفحه خطایی رخ داده است مواجه می شویم میرویم

**Comment by sahar-shafiee** [comment]
@PouryaMansouri @likecodingloveproblems 
بی زحمت یک زمان نیز به من بدهید که چقدر طول میکشه چون این ارور از سمت تیم مارکتینگ مطرح شده و می خواهند بدانند چه زمانی تسک انجام میشه

**Comment by likecodingloveproblems** [comment]
please define get_absolute_url for shop model @PouryaMansouri

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems I have done the issue, Please review the pull request,
