### ISSUE TITLE
publishing products that their shops are unpublished

### ISSUE THREAD

**Issue by likecodingloveproblems** [nakhll-company/nakhll_backend#243]
Shops that are not published, their products are shown in market.

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh please design the shop and product unpublish pages.

**Comment by MaryamSamareh** [comment]
> @MaryamSamareh please design the shop and product unpublish pages.

لطفا یه توضیح درمورد این تسک میشه بفرمایید
طراحی صفحه شاپ و محصولاتی که پابلیش نشده اند در پروفایل کاربر؟

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh we discuss it in the daily meeting.

**Comment by likecodingloveproblems** [comment]
@milad7212, please put all end point's that are related to this issue here
endpoints that are shown to the end user

**Comment by MaryamSamareh** [comment]
طراحی صفحه در دست انجام است (تیم محتوا در حال طراحی تصویری مشابه با صفحه ارور 404 هستند)
فرایند کلی: تصویر طراحی شده با مضمون اینکه "محصول(حجره) ای که به دنبال آن بودید دیگر در سایت وجود ندارد" به کاربر نمایش داده می شود.
در پایین صفحه لیستی از محصولات(حجره های) پیشنهادی به کاربر که با محصول(حجره) غیرفعال تطابق بیشتری داشته باشند به کاربر پیشنهاد داده می شود تا در صورت تمایل از آنها بازدید کند.

در حد امکان باید تمامی صفحاتی که به محصول(حجره) لینک می دهند اصلاح شده و لینک مربوطه از آنها حذف شود.
لیست صفحاتی که امکان لینک به محصول را دارند:
صفحه محصولات
سرچ
پیشنهادات
ترب و یکتانت و..

لیست صفحاتی که به حجره لینک می دهند:
صفحه جزییات محصول
سرچ اسم حجره (که در حال حاضر با غیرفعال شدن حجره، دیگر با سرچ نمیتوان به صفحه حجره دست پیدا کرد)

پیشنهاد: یه صفحه دلایل (تحت عنوان: چرا این اتفاق افتاده است) هم طراحی شود که دلایلی که یک محصول یا حجره غیرفعال می شود در آن قرار بگیرد تا در صورت تمایل کاربر بتواند آن را مطالعه کرده و از دلیل این اتفاق آگاه شود. (برای جلوگیری از گیج شدن کاربر)

@likecodingloveproblems
 لطفا دلایلی که محصول یا حجره ای در سایت غیرفعال می شود را بفرمایید

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh این مساله رو باید اقای بنازاده یا اقای مهدوی پاسخ بدن.
