### ISSUE TITLE
Unauthorized access for some of accounting views

### ISSUE THREAD

**Issue by mohsenone** [nakhll-company/nakhll_backend#35]
Some of views in accounting module which returns excel file of database, doesn't have any group restriction, so any logged in user (or maybe even normal users) can download them

Please add appropriate ```group_required``` field to them, and also don't forget to add proper argument summary in doc string

**Comment by likecodingloveproblems** [comment]
as these links aren't public, and we directly send them to the team, so I think it's not a problem, except when a bot scrap all our links!

and I think it does not create any problem in the happy path of operations, So I thought it's not a bug, it's a feature ;)

**Comment by likecodingloveproblems** [comment]
As @PouryaMansouri had an interesting work on the Admin panel, we can transfer the accounting app to those panels specific to each team, and give them a nice UI and searching, filtering, logging and many other functionalities...

**Comment by likecodingloveproblems** [comment]
I close this issue, hope to remove accounting app by dashboards @PouryaMansouri will create.
