### ISSUE TITLE
SEO issue - Redirect all /blog requests

### ISSUE THREAD

**Issue by adelisardo** [nakhll-company/nakhll_backend#405]
سلام
لطفا ساختاری پیاده کنید که تمامی درخواست های
https://nakhll.com/blog/
به آدرس زیر با کد 301 منتقل شوند (Redirect) شوند.
https://nakhll.com/mag/

For example: 
https://nakhll.com/blog/5054/test/  (301 redirect)=> https://nakhll.com/mag/5054/test/ 
هدف از انجام این درخواست برای حذف لینک های قدیمی و حفظ وضعیت SEO فعلی است.

**Comment by likecodingloveproblems** [comment]
please test it. @adelisardo
