### ISSUE TITLE
referral_link to referral_code 

### ISSUE THREAD

**Issue by adelisardo** [nakhll-company/nakhll_backend#406]
با توجه به صحبت شفاهی انجام شد، به این نتیجه رسیدیم که API به جای ارسال لینک، کد رفرال را ارسال کند و UI با توجه به این کد، URL مورد نظر ساخته و به کاربر نمایش داده می شود.
نکته: لطفا در زمان Deployment به این موضوع که issue متناظر در frontend نیز تکمیل شده باشد توجه فرمایید.

**Comment by likecodingloveproblems** [comment]
- [ ] restapi.serializer.ProfileSerializer
- [ ] nakhll_market.serializers.NewProfileSerializer

**Comment by likecodingloveproblems** [comment]
@adelisardo this data is returned in two endpoint, it seems one of them is enough, so please decide about it.

**Comment by saman7799** [comment]
این ایشو در فرانت و بک انجام شد.
