### ISSUE TITLE
The discount code error

### ISSUE THREAD

**Issue by adelisardo** [nakhll-company/nakhll_backend#419]
لطفا علت خطای کد تخفیف را بررسی و اعلام نمایید
"هنگامی که کاربر از طریق پاپ آپ ثبت نام می کند و می خواهد خرید خود را ثبت دهد، وارد سبد خرید می شود و کدتخفیف خود را اعمال می کند ارور می دهد و کد تخفیفی که اعمال نمی شود :nakhll74

**Comment by likecodingloveproblems** [comment]
In coupon constraint, max_usage is set to 5, and it's used 5 time.
it's not a bug, it's feature ;)

**Comment by likecodingloveproblems** [comment]
I close this issue as it seems solved.
