### ISSUE TITLE
Requirements cleanup

### ISSUE THREAD

**Issue by PouryaMansouri** [nakhll-company/nakhll_backend#43]
- [ ] check requirements .
- [ ] delete all unused libraries .

**Comment by likecodingloveproblems** [comment]
we have many dependencies that are out of date and may be deprecated nearly.
so by your permission @PouryaMansouri I change the title to **dependency cleanup**
- [ ] remove unused dependencies
- [ ] update dependencies

**Comment by likecodingloveproblems** [comment]
we must implement dashboards by the Django admin panel to remove ExcelResponse and the accounting app.

**Comment by PouryaMansouri** [comment]
We have many libraries in requirements, I think we should check this file and delete all useless lib.

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri 
we also need to split DEVELOPMENT from the PRODUCTION environment, we have some packages useful in DEVELOPMENT but useless in PRODUCTION.
