### ISSUE TITLE
بررسی ساختار ارور صفحه تنظیمات

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#45]
ارورها در صفحه تنظیمات از سمت بک به شکل زر برگردانده می شوند

`{"FK_ShopManager":{"User_Profile":{"NationalCode":["مطمعن شوید طول این مقدار بیشتر از 10 نیست."]}}}`
در حالیکه ساختار اروری که با فرانت بسته شده است به شکل زیر می باشد

`{
    "error_key_1": [
        "error_message_1",
        "error_message_2",
        ...
    ],
    "error_key_2": [
        "error_message_1",
        "error_message_2",
        ...
    ],
    ...
}`

**Comment by PouryaMansouri** [comment]
please send me all APIs that front call for the shop's settings.
@sahar-shafiee

**Comment by PouryaMansouri** [comment]
@sahar-shafiee We need to have a voice call about this issue.

**Comment by PouryaMansouri** [comment]
@sahar-shafiee @milad7212 
این مورد رو ببندم ؟

**Comment by sahar-shafiee** [comment]
@PouryaMansouri 
روی سایت اصلی من تست میکنم برای کد ملی هیچ اروری نمایش داده نمیشه

**Comment by milad7212** [comment]
ببندینش
