### ISSUE TITLE
مشکل تغییر مشخصات و ادرس برای حجره

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#51]
در پنل حجره داری قسمت تنظیمات با تنظیم مشخصات و ادرس برای یک حجره تمامی حجره های دیگر متعلق به ان حجره دار نیز همان مقدار را می گیرند.

**Comment by PouryaMansouri** [comment]
@milad7212 
please give me the API you called.

**Comment by PouryaMansouri** [comment]
The problem is front sends the wrong JSON,
instead of updating the shop's address, it is updating the user_profile's address.

**Comment by milad7212** [comment]
Thank. I will check
