### ISSUE TITLE
ذخیره اپدیت انجام شده در تنظیمات حجره

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#52]
هر بخشی از تنظیمات حجره را که اپدیت میکنیم هیچکدام ذخیره نمی شود.( ارور به هنگام به روز رسانی تنظیمات حجره)

**Comment by PouryaMansouri** [comment]
I should check this API:

https://nakhll.com/api/v1/shop/%D8%AD%D8%AC%D8%B1%D9%87-%D8%AC%D8%AF%DB%8C%D8%AF/settings/

**Comment by PouryaMansouri** [comment]
@milad7212 
everything looks OK, please give me error sample

**Comment by PouryaMansouri** [comment]
@MaryamSamareh 
Please check it again.

**Comment by MaryamSamareh** [comment]
تست شد
مشکل برطرف شده است
