### ISSUE TITLE
حذف عکس پروفایل حجره

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#53]
امکان حذف عکس پروفایل حجره وجود ندارد و فقط میتوان ان را اپدیت کرد

**Comment by saman7799** [comment]
@PouryaMansouri 
I think @likecodingloveproblems  should comment on this

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
What is your opinion about it?

**Comment by PouryaMansouri** [comment]
@MaryamSamareh @sahar-shafiee 
Please test it again.

**Comment by MaryamSamareh** [comment]
همچنان عکس پروفایل حجره حذف نمی شود اما پیام "به روز رسانی با موفقیت انجام شد" نمایش داده می شود.

**Comment by PouryaMansouri** [comment]
@MaryamSamareh 
please test it again

**Comment by PouryaMansouri** [comment]
this issue is waiting to accepted PR by @likecodingloveproblems

**Comment by likecodingloveproblems** [comment]
> @likecodingloveproblems What is your opinion about it?

ohhh sorry, I don't see this :disappointed:
