### ISSUE TITLE
ثبت حجره های تکراری

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_backend#56]
امکان ثبت حجره با نام های تکراری وجود دارد. حتی زمانی که شهر یکسان داشته باشند.

**Comment by PouryaMansouri** [comment]
I think this issue was solved in the past.
 
@likecodingloveproblems 
??

**Comment by PouryaMansouri** [comment]
@MaryamSamareh 
Please check it again.

**Comment by MaryamSamareh** [comment]
تست شد
برطرف شده است
