### ISSUE TITLE
حذف تصاویر محصول

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_backend#57]
اگر محصول بیش از 3 تصویر داشته باشد و یکی از تصاویر غیراصلی حذف شود، همه ی تصویرهای دیگر به جز تصویر اصلی هم حذف می شود.

**Comment by PouryaMansouri** [comment]
@milad7212 @sahar-shafiee 
Which API does call to delete the product image?

**Comment by sahar-shafiee** [comment]
> @milad7212 @sahar-shafiee Which API does call to delete the product image?
همه ی عکس ها داخل این ای پی ای ارسال می شوند
http://localhost:8000/api/v1/shop/neil-market-food-store/products/
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
@sahar-shafiee 
Do you call this API to delete one image?

**Comment by sahar-shafiee** [comment]
@PouryaMansouri   no

**Comment by PouryaMansouri** [comment]
Please Give me the  API that you used to delete one image.
@sahar-shafiee

**Comment by sahar-shafiee** [comment]
@PouryaMansouri  اقای منصوری من همین مسئله رو می خواستم روی لوکال تست کنم که ای پی ای خطا میداد نتونستم تست کنم ببینم مشکل چیه 
الان روی سرور تست کردم متوجه شدم وقتی در حالت ویرایش یکی از عکس های محصول به غیر از عکس اصلی حذف شود property Product_Banner خالی برای بک ارسال میشه
برای حذف عکس ها ای پی ای جداگانه ای وجود ندارد و این مشکل فرانتی هست

**Comment by PouryaMansouri** [comment]
Thanks:hand:

**Comment by PouryaMansouri** [comment]
در سمت بک کاری نباید کرد. همه چی درسته 
در فرانت باید عکس دوباره به صورت base64 در بیاید

این رو منم پیدا کردم. کمکی می کنه: 
https://stackoverflow.com/questions/22172604/convert-image-from-url-to-base64

**Comment by sahar-shafiee** [comment]
@PouryaMansouri okay thank you
