### ISSUE TITLE
ثبت روش ارسال پس کرایه

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_backend#58]
اگر به شهر خاصی ارسال نداشته باشیم بازهم زمان سفارش برای کاربر پس کرایه ثبت می شود.

**Comment by PouryaMansouri** [comment]
This issue was done, 
We wait to push the code to the production server.
@likecodingloveproblems

**Comment by PouryaMansouri** [comment]
@MaryamSamareh 
Please check it again.

**Comment by MaryamSamareh** [comment]
تست شد
برطرف شده است
