### ISSUE TITLE
change address's fields

### ISSUE THREAD

**Issue by PouryaMansouri** [nakhll-company/nakhll_backend#59]
What are the problems:

1. All data should be checked that they are correct or not.
2. change new field data to this same address id in FK models.
3. All address fields are char fields and all of them should change to FK fields.
4. change the serializers.

Does anyone have any comments?

**Comment by milad7212** [comment]
:+1:

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri you mean modifying cities as references not as embed data?
that's OK, I will suggest a patch for it :)

**Comment by likecodingloveproblems** [comment]
User problem that sees city, bigcity, state id instead of name is locked by this issue? @PouryaMansouri @milad7212

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
you are in progress with this issue on other issues.
