### ISSUE TITLE
clean branches

### ISSUE THREAD

**Issue by PouryaMansouri** [nakhll-company/nakhll_backend#60]
We should have only had this branch:

- main: production branch
- develop: a branch that all developers work on it
- release: create from develop branch for testing and final check before release production
- fix-bug: for fixing bugs from main.
- feature: for add new features
- branch make from issues.

this issue task:
- [ ] all the other branches should be deleted as soon as possible.
- [ ] issue and feature branch should be deleted after accepting their pull request.

this is the git-flow structure.

@likecodingloveproblems

**Comment by likecodingloveproblems** [comment]
I doubt you have done this @PouryaMansouri

**Comment by PouryaMansouri** [comment]
Yes. Please merge all pull requests with develop branch
