### ISSUE TITLE
import product

### ISSUE THREAD

**Issue by PouryaMansouri** [nakhll-company/nakhll_backend#62]
instead of CSV, get an array from the front for import products.

**Comment by PouryaMansouri** [comment]
@sahar-shafiee 
What is the API?

**Comment by sahar-shafiee** [comment]
@PouryaMansouri 
اقای منصوری بی زحمت اجازه بدین در این مورد یک صحبتی با اقای مهدی زاده داشته باشیم . اگر اوکی دادن بعد شما روش وقت بزارین

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri اقای منصوری بی زحمت اجازه بدین در این مورد یک صحبتی با اقای مهدی زاده داشته باشیم . اگر اوکی دادن بعد شما روش وقت بزارین

OK

**Comment by likecodingloveproblems** [comment]
> @PouryaMansouri اقای منصوری بی زحمت اجازه بدین در این مورد یک صحبتی با اقای مهدی زاده داشته باشیم . اگر اوکی دادن بعد شما روش وقت بزارین

@sahar-shafiee Is it done?

**Comment by sahar-shafiee** [comment]
> > @PouryaMansouri اقای منصوری بی زحمت اجازه بدین در این مورد یک صحبتی با اقای مهدی زاده داشته باشیم . اگر اوکی دادن بعد شما روش وقت بزارین
> 
> @sahar-shafiee Is it done?

@likecodingloveproblems اقای مهدی زاده فرانتش خیلی وقته انجام شده ولی موقع ارسال داده ها به بک و دوباره تبدلیش به csv سخته اگر به صورت ارایه ای از ابجکت ها داده ها رو بشه برای بک ارسال کرد خیلی راحتتر . می خواستم بدونم اینکار رو انجام بدیم یا نه؟

**Comment by likecodingloveproblems** [comment]
I don't have any idea, so go your way
@sahar-shafiee @PouryaMansouri

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems @sahar-shafiee 
I will check it tomorrow.
