### ISSUE TITLE
عدم نمایش فاکتورهای "در انتظار پرداخت" در پنل حجره دار

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#63]

**Comment by PouryaMansouri** [comment]
@milad7212 @sahar-shafiee 
Which API did you call?

**Comment by PouryaMansouri** [comment]
@milad7212 
Please add the API here

**Comment by sahar-shafiee** [comment]
https://nakhll.com/api/v1/shop/neil-market-food-store/invoices/?is_completed=false

فکر میکنم این مسئله برطرف شده باشه اما بی زحمت شما یک بررسی کنید
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
> https://nakhll.com/api/v1/shop/neil-market-food-store/invoices/?is_completed=false
> 
> فکر میکنم این مسئله برطرف شده باشه اما بی زحمت شما یک بررسی کنید @PouryaMansouri

من دیتایی برای تست ندارم
خانم هاشمی لطفا شما تست کنید
@MaryamSamareh

**Comment by MaryamSamareh** [comment]
برطرف شده
