### ISSUE TITLE
بازگرداندن کوپن تخفیف در صورت پرداخت ناموفق

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#64]

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri please mention all scenarios and problems you have in mind.
@MaryamSamareh please clean this issue. consult with Mohammad Banazadeh (CEO)

**Comment by MaryamSamareh** [comment]
> Reference in new

ok, I'll do this.

**Comment by PouryaMansouri** [comment]
مواردی که باید توجه شود : 
۱- اگر کوپن تخفیف برگردد یعنی دوباره در حالت اعمال شده قرار داشته باشد ؟  در این مورد اگر تاریخ کوپن بگذرد باز عمل می کند.
۲- آیا کوپن تخفیف های با محدودیت مصرف باید تعداد دفعلات مصرف آنها برگشت پیدا کند

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems @MaryamSamareh 

I am still waiting for a response.

**Comment by MaryamSamareh** [comment]
> @likecodingloveproblems @MaryamSamareh
> 
> I am still waiting for a response.

and I am still waiting for a response from Mr. Banazade, too!

**Comment by MaryamSamareh** [comment]
@PouryaMansouri 
طبق گفته ی آقای بنازاده، کوپن فقط در صورتی باید از بین برود که از آن استفاده شده باشد.
پس در مورد اول، اگر کوپن تاریخش گذشت نباید تمدید شود اما تا زمانی که تاریخ دارد درصورت پرداخت ناموفق باید برای کاربر دوباره فعال باشد
2- باید کوپن هایی که در پرداخت های ناموفق اعمال شده اند دوباره به حساب کاربر برگردند و تعداد آنها در محدودیت دفعات مصرف محاسبه نشود

**""آقای بنازاده اولویت بسیار بالا برای این تسک تعریف کردند""**

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri طبق گفته ی آقای بنازاده، کوپن فقط در صورتی باید از بین برود که از آن استفاده شده باشد. پس در مورد اول، اگر کوپن تاریخش گذشت نباید تمدید شود اما تا زمانی که تاریخ دارد درصورت پرداخت ناموفق باید برای کاربر دوباره فعال باشد 2- باید کوپن هایی که در پرداخت های ناموفق اعمال شده اند دوباره به حساب کاربر برگردند و تعداد آنها در محدودیت دفعات مصرف محاسبه نشود
> 
> **""آقای بنازاده اولویت بسیار بالا برای این تسک تعریف کردند""**

ممنون.
@MaryamSamareh 
سوال من اینجاست که کوپن تخفیف اعمال شده در سبد خرید بماند یا نه حذف شود و بعد دوباره فرد کوپن تخفیف را اعمال کند.
چون در یکی از باگ های قبل به من گفته شد که کوپن تخفیف اعمال شده باقی می ماند برای همیشه و باید حذف شود.

**Comment by MaryamSamareh** [comment]
@PouryaMansouri 
هر زمانی که کاربر از صفحه وارد کردن کوپن تخفیف خارج شد باید کوپن تخفیف از این صفحه حذف شود
حالا می تواند این خروج از صفحه به دلیل وارد شدن به صفحه پرداخت باشد (هم پرداخت موفق و هم ناموفق) و هم بازگشت به صفحات دیگر سایت. در هر صورت باید کوپن اعمال شده حذف شود.

**Comment by PouryaMansouri** [comment]
@MaryamSamareh 
ممنون

**Comment by MaryamSamareh** [comment]
@PouryaMansouri 
این مسئله بر روی سایت اصلی تست شد و به درستی عمل می کند. در نتیجه من این ایشو را می بندم.

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri این مسئله بر روی سایت اصلی تست شد و به درستی عمل می کند. در نتیجه من این ایشو را می بندم.

عالی . تشکر
