### ISSUE TITLE
اصلاح کوپن های در دسترس

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#67]

**Comment by PouryaMansouri** [comment]
@saman7799 @sahar-shafiee @MaryamSamareh 
What should I do?

**Comment by sahar-shafiee** [comment]
این تسک قبلا به درخواست اقای حسنی ایجاد شده است. لطفا صحبتی با ایشان داشته باشید اگر مسئله حل شده است بی زحمت ایشو را ببندید
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
this was a test for developers.
