### ISSUE TITLE
باگ حذف شدن عکسهای حجره

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#69]
عکس محصولات بعد از بارگذاری و گذشت چند روز حذف شدند و عکس محصولات نیست(حجره نیل مارکت و گالری آنتیک7،سرای مس،کتابرسان)

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
I think you should check the database in this case too.

**Comment by PouryaMansouri** [comment]
Did you check this issue?

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
Did you check this issue?

**Comment by likecodingloveproblems** [comment]
I'll check it

**Comment by likecodingloveproblems** [comment]
I query shops that haven't any image in the database and their related field value is an empty string in a CSV file.
[product_without_image.csv](https://github.com/nakhll-company/nakhll_backend/files/8769011/product_without_image.csv)

**Comment by likecodingloveproblems** [comment]
But these shops are not in them!

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee Can you mention a product for sample?

**Comment by sahar-shafiee** [comment]
![3](https://user-images.githubusercontent.com/52815608/170238255-655d67bc-1001-4f10-832b-a7c2fd205a5f.JPG)
![2](https://user-images.githubusercontent.com/52815608/170238266-cb2ad1b8-c41b-465b-b1f8-ad457b10bc68.JPG)
![1](https://user-images.githubusercontent.com/52815608/170238268-77ad7922-9c58-4a9f-b74a-b1e5578d507d.JPG)

**Comment by likecodingloveproblems** [comment]
thanks a lot @sahar-shafiee

**Comment by likecodingloveproblems** [comment]
@please test it

- [ ] remove nested media directory
