### ISSUE TITLE
خطای ناموجود بودن محصول به فرمت صحیح نمی باشد

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#70]

**Comment by PouryaMansouri** [comment]
@saman7799 @MaryamSamareh @sahar-shafiee 
could you please give me an example?

**Comment by sahar-shafiee** [comment]
این مسئله مربوط به نمایش پیام های ناموجود بودن محصول است که تصحیح شده است. برای همین من این ایشو رو میبندم.
@PouryaMansouri
