### ISSUE TITLE
باگ محدوده ارسال

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#71]
حجره دار محدوده ارسال برای حجره شون مشخص کردند (فقط محدوده کرمان را انتخاب کردند)اما کاربر شهرهای دیگر هم میتواند سفارش را ثبت دهد

**Comment by PouryaMansouri** [comment]
This bug was resolve

In logistec/interface.py:
line: 151
I add : len(all_lus) != 0:
