### ISSUE TITLE
category null in upadte product

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#72]
محصولاتی که به صورت گروهی بارگزاری شده اند شناسه دسته بندی ها در ستونی به نام new-category-id ثبت شده است.
در موقع ویرایش این محصولات مقدار category انها null می باشد و کاربر نمی تواند محصول را ویرایش کند

**Comment by likecodingloveproblems** [comment]
@sahar-shafiee  متاسفانه ستون new-category خذف شده و دیتاشون موجود نیست
اما فعلا در اولین قدم من schema رو اصلاح کردم
به نظر میاد فازی که جابجایی از new-category به category رو انجام داده باید رفرنس های new-category رو هم اصلاح میکرده، اما اگر اینجوری نباشه باید اون ها هم اصلاح بشن.

**Comment by sahar-shafiee** [comment]
@likecodingloveproblems 
الان حجره قطعات لوازم خانگی هنوز هیچکدام از محصولاتش دسته بندی ندارند
الان اگر بخواهند ویرایش گروهی انجام دهند ایدی دسته بندی باید داخل ستونی با نام category_id قرار گیرد؟

**Comment by sahar-shafiee** [comment]
@PouryaMansouri 
اقای منصوری پول ریکوئست این ایشو رو شما بررسی کردین؟
بی زحمت هر وقت روی سایت اصلی رفت به من اطلاع بدین تا به بچه های عملیات خبر بدهم

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri اقای منصوری پول ریکوئست این ایشو رو شما بررسی کردین؟ بی زحمت هر وقت روی سایت اصلی رفت به من اطلاع بدین تا به بچه های عملیات خبر بدهم

@likecodingloveproblems 
من فقط approve میکنم. مرج کردن با خود محمدعلی هست.
