### ISSUE TITLE
ساختار ارور در صفحه ایجاد و ویرایش محصول

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#73]
ارورهایی که از سمت بک برمیگردند مثل وقتی که عکس خالی است اگرمتن ارور تغییر کند کاربر بهتر متوجه میشود
{"Image":["این مقدار نباید توهی باشد."]}

**Comment by PouryaMansouri** [comment]
> ارورهایی که از سمت بک برمیگردند مثل وقتی که عکس خالی است اگرمتن ارور تغییر کند کاربر بهتر متوجه میشود {"Image":["این مقدار نباید توهی باشد."]}

I done some change in issue 47. you can test the result on it's branch.

**Comment by PouryaMansouri** [comment]
@sahar-shafiee 
I had changed the error message for null image and category, Please check the new style and if it is ok, I add this style to other fields.

**Comment by MaryamSamareh** [comment]
تست شد
مشکل برطرف شده است
