### ISSUE TITLE
ارورهایی که ای پی ای کوپن در صفحه فاکتور برمیگرداند روی وضعیت 200 برمیگردد و صحیح نمی باشند

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#76]

**Comment by MaryamSamareh** [comment]
4. دو کوپن روی کل سبد خرید می توان اعمال کرد درحالی که باید تنها یک کوپن روی کل سبد خرید اعمال شود.

**Comment by MaryamSamareh** [comment]
5. زمانی که کوپن تخفیف اعمال می شود اما وارد صفحه پرداخت نمی شویم و بعد از مدتی دوباره به سبد خرید برمیگردیم همچنان کد تخفیف ها وجود دارند.
یعنی اگر از کد تخفیف استفاده نکنیم، هر زمان دیگری که به سبد خرید برگردیم هنوز کدتخفیف روی سبد خرید اعمال شده است.

**Comment by MaryamSamareh** [comment]
@PouryaMansouri 
این اشکال آخر (شماره 5) قبلا حل شده بود اما دوباره برگشته.
اگه ممکنه یه بررسی کنید لطفا
