### ISSUE TITLE
بررسی محصولات ناموجود

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#78]
محصولی که عکس آن اضافه شده است اگر روی دکمه ی افزودن به سبد خرید زده شود پیام محصول در دسترس نیست نمایش داده می شود ولی وقتی صفحه جزئیات محصول رو باز میکنیم نوشته شده که یک عدد باقی مانده است

**Comment by MaryamSamareh** [comment]
متوجه نشدم چه مشکلی را باید تست کنم

**Comment by saman7799** [comment]
ببخشید توضیحش ثبت نشده بود
که عکس آن اضافه شده است اگر روی دکمه ی افزودن به سبد خرید زده شود پیام محصول در دسترس نیست نمایش داده می شود ولی وقتی صفحه جزئیات محصول رو باز میکنیم نوشته شده که یک عدد باقی مانده است
@MaryamSamareh

**Comment by MaryamSamareh** [comment]
اگه منظور از محصول، کتاب عبدالمهدی است هنوز هم در همین وضعیت است

**Comment by PouryaMansouri** [comment]
من فکر میکنم این مشکل حل شده از قبلا ولی کد بالا نرفته. من چیزی ندیدم تو بک برای این مشکل.
شاید دیتابیس من کامل نیست.

**Comment by PouryaMansouri** [comment]
و این جمله رو متوجه نمیشم :‌"محصولی که عکس آن اضافه شده است" ؟
مشکل اینه کالای نا موجود رو داریم میبینیم در سایت یا مشکل بعد اضافه شده عکس اتفاق می افتد؟

**Comment by sahar-shafiee** [comment]
@PouryaMansouri @likecodingloveproblems 

داخل سایت یکسری محصول وجود دارد که حجره ی آن محصول پایین آورده شده ولی محصولات آن حجره در سایت نمایش داده می شوند ولی این محصولات دکمه خرید برایشان نمایش داده نمی شود چون property saleable انها false است ولی در سایت وقتی نگاه میکنید نوشته شده که از این محصول یک عدد باقی مانده ولی دکمه ی خرید نمایش داده نمی شود . مثل کتاب المهدی

**Comment by PouryaMansouri** [comment]
@MaryamSamareh @sahar-shafiee 
This problem was solved, Please check it again.

**Comment by MaryamSamareh** [comment]
مشکل متاسفانه هنوز پابرجاست
![image](https://user-images.githubusercontent.com/48446254/168956283-e9e400dd-460b-4b84-908f-8492ac7148b2.png)

**Comment by MaryamSamareh** [comment]
@PouryaMansouri 
در تصویر بالا مشخص است کتابی که موجودی آن یک عدد نوشته شده ولی دکمه خرید ندارد. (حجره آن بسته شده است)

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri در تصویر بالا مشخص است کتابی که موجودی آن یک عدد نوشته شده ولی دکمه خرید ندارد. (حجره آن بسته شده است)
فقط همین یک حجره هست؟
مورد دیگری مشاهده شده؟

**Comment by MaryamSamareh** [comment]
من تا به حال مورد دیگری ندیده ام
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
I think this shop had some wrong data in the database,
could you please check this shop data in the database?

**Comment by PouryaMansouri** [comment]
@MaryamSamareh 
please search the website to find another product in the same situation.

**Comment by MaryamSamareh** [comment]
![image](https://user-images.githubusercontent.com/48446254/169634776-609d05ab-73cb-408d-89ae-fad597bbc12d.png)
این محصول هم به طور مشابهی از حجره لوازم خانگی یاس هست که حجره اش ظاهرا پایین آمده ولی محصولاتش هنوز در سایت موجود هستند
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
> ![image](https://user-images.githubusercontent.com/48446254/169634776-609d05ab-73cb-408d-89ae-fad597bbc12d.png) این محصول هم به طور مشابهی از حجره لوازم خانگی یاس هست که حجره اش ظاهرا پایین آمده ولی محصولاتش هنوز در سایت موجود هستند @PouryaMansouri

کنار این محصول شده که ناموجود است و امکان سفارش ازش نیست.

به نظر درست میاد.

موردی که امکان سفارش ازش باشد ولی موجود نباشد داریم؟ مشکل کتاب قبلی که گفتید

**Comment by PouryaMansouri** [comment]
![image](https://user-images.githubusercontent.com/54346362/169635461-267273ea-2e0c-48a5-9148-067c3575251e.png)

@MaryamSamareh 
در سایت بصورت درست گفته شده  موجودی این کالا

**Comment by PouryaMansouri** [comment]
> مشکل متاسفانه هنوز پابرجاست ![image](https://user-images.githubusercontent.com/48446254/168956283-e9e400dd-460b-4b84-908f-8492ac7148b2.png)

@likecodingloveproblems 
In my opinion, we have a problem with the data of this product in the database.
Please check this product's data.

**Comment by MaryamSamareh** [comment]
@PouryaMansouri 
با سرچ کردن محصولات و برداشتن تیک "فقط محصولات موجود" می توان محصولات آزادی استور را هم دید که حجره اش پایین رفته ولی محصولات هنوز موجود هستند درحالی که دکمه خرید ندارند
مثلا من "کروسان" سرچ کردم

**Comment by MaryamSamareh** [comment]
@PouryaMansouri 
[https://nakhll.com/shop/mahbanoojan/product/m7/](url)
[https://nakhll.com/shop/%D8%A2%D8%B2%D8%A7%D8%AF%DB%8C-%D8%A7%D8%B3%D8%AA%D9%88%D8%B1/product/%D9%86%D8%A7%D9%86-%DA%A9%D8%B1%D9%88%D8%B3%D8%A7%D9%86-%D8%A8%D8%A7-%D9%85%D8%BA%D8%B2-%D8%B4%DA%A9%D9%84%D8%A7%D8%AA%DB%8C-%D9%BE%DA%86-%D9%BE%DA%86/](url)

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri I will check it.
