### ISSUE TITLE
باگ آزادی استور در قسمت لجستک ارسال به شهرهای غیر از کرمان

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#79]

**Comment by MaryamSamareh** [comment]
حجره آزادی استور در سایت پایین آمده است
اما من این باگ را با حجره ی خودم تست کردم و همچنان پس کرایه ثبت می شود.
نکته: روی سایت تست کردم نه لوکال.

**Comment by PouryaMansouri** [comment]
این مشکل حل شده. انتقال میدم به حالت  review in progress
@likecodingloveproblems 
لطفا بررسی کنید

**Comment by PouryaMansouri** [comment]
@MaryamSamareh 
Please check it again.

**Comment by MaryamSamareh** [comment]
تست شد
درست عمل می کند.
به جز اینکه من در سبد خریدم محصولات دیگری هم داشتم که باید به شهر مقصد من ارسال می شدند. اما ارور "هیچ واحد ارسالی برای شهر شما تعریف نشده است" به من نشان داده شد و من مجبور شدم دوباره از اول برگردم و سبد خریدم را تایید کنم
