### ISSUE TITLE
HubSpot API

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#81]
اقای سید مهدوی می خوان قابلیت های هاب اسپات توسط تیم فنی بررسی بشه.

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
من نظری در موردش ندارم. فکر کنم شما تجربه بیشتری دارید

**Comment by likecodingloveproblems** [comment]
باید اولویت بندی بشه ابتدا @saman7799 
باید ای پی آی HubSpot بررسی بشه به نظر میاد بیشتر سمت فرانت باشه البته من تو این زمینه تجربه ای ندارم.

**Comment by saman7799** [comment]
بله همانطور که مشخص هست این ایشو تگ بک لاگ داره و همانطور که توضیح داده شد باید ابتدا بررسی بعد اولویت زده شود
@likecodingloveproblems
