### ISSUE TITLE
فایل های اکسل مورد نیاز

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#82]

**Comment by sahar-shafiee** [comment]
https://nakhll.com/accounting/user-stats/
https://nakhll.com/accounting/shop-info/
https://nakhll.com/accounting/shop-logistic-stats/
https://nakhll.com/accounting/shop-managers-info/
https://nakhll.com/accounting/shop-managers-info/v2/
https://nakhll.com/accounting/user-mobile/ (error 500)
https://nakhll.com/accounting/product-stats/ (error 500)
https://nakhll.com/accounting/invoice-stats/
https://nakhll.com/accounting/buyers-info/
https://nakhll.com/accounting/invoices-info/
https://nakhll.com/accounting/sale-data/  (error 500)
https://nakhll.com/accounting/item-data/  (error 500)
لیست لینک های موجود برای دریات فایل اکسل لطفا مواردی که خطای 500 میده رو برطرف کنید

@PouryaMansouri

**Comment by PouryaMansouri** [comment]
https://nakhll.com/accounting/user-mobile/   -> Donw

**Comment by PouryaMansouri** [comment]
https://nakhll.com/accounting/product-stats/

this link was OK and just need to login into the admin panel.

**Comment by PouryaMansouri** [comment]
https://nakhll.com/accounting/sale-data/ 

@sahar-shafiee 
we don't have any view for this link.
remove this link

**Comment by PouryaMansouri** [comment]
https://nakhll.com/accounting/item-data/
@sahar-shafiee 
remove this link too, we don't have this link in our app

**Comment by PouryaMansouri** [comment]
please check the PR: https://github.com/nakhll-company/nakhll_backend/pull/102

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
please check the PR: https://github.com/nakhll-company/nakhll_backend/pull/102

**Comment by PouryaMansouri** [comment]
@sahar-shafiee , Please check the links and if Ok, I close this issue

**Comment by sahar-shafiee** [comment]
@PouryaMansouri 
بررسی شد
همه لینگ ها صحیح کار میکنند
