### ISSUE TITLE
پاک کردن و ادغام ویوها و سریلایزرها و استاندارد کردن ادرس ها

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#83]

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri feel free to move it to In **progress bar** :stuck_out_tongue_winking_eye:

**Comment by likecodingloveproblems** [comment]
what's the status of this task?
if you have not started this, please move it to **to do** and focus on **priority 1** and **bug** label. @PouryaMansouri

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri feel free to move it to In **progress bar** stuck_out_tongue_winking_eye

You said that move it on in progress !!!!
OK

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
Please set priority
