### ISSUE TITLE
تغییر ساختار مبلغ و مبلغ تخفیف و تغییر از ریال به تومان

### ISSUE THREAD

**Issue by saman7799** [nakhll-company/nakhll_backend#84]

**Comment by likecodingloveproblems** [comment]
It's dependent on database redesign, I am thinking of it.

**Comment by likecodingloveproblems** [comment]
@mohsenone Do you think this issue is critical, it does not have any business value, the problem is only technical.

**Comment by likecodingloveproblems** [comment]
CLOSED AS LACK OF ACTIVITY
