### ISSUE TITLE
Check postman on main branch

### ISSUE THREAD

**Issue by PouryaMansouri** [nakhll-company/nakhll_backend#86]

**Comment by PouryaMansouri** [comment]
- [ ] Cart
- [x] User cart -> 200
- [x] Add Product to cart -> 201
- [x] Reduce cart items from cart -> 200
- [x] Remove cart items from cart -> 200
- [x] Pay Cart -> OK 
- [x] Set Cart address -> 200
- [x] Set Coupon -> 200
- [x] Unset Coupon -> 200

- [ ] Confirm Cart Changes -> 404
- [ ] Test Verify payment -> 404

**Comment by PouryaMansouri** [comment]
# cart/Archive

This is an archive folder and its request does not work.

**Comment by likecodingloveproblems** [comment]
Keep it up :clap:

**Comment by PouryaMansouri** [comment]
# Landing

- [x] landing page last created products -> 200
- [ ] landing page amazing products -> 404
- [ ] **landing page most-sold-shops -> 500**
- [x]  landing page last created discounted products -> 200
- [ ] landing page categories -> 404
- [x] landing page most-discount-prec-products -> 200 
- [x] landing page random-shops -> 200
- [x] landing page random-products -> 200
- [x]  landing page sliders -> 200
- [x] most sold product -> 200

**Comment by PouryaMansouri** [comment]
# Category

- [x]  All Categories -> 200
- [x] Category Details -> 200
- [x] Categories with products count -> 200

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri please close this if is done?

**Comment by PouryaMansouri** [comment]
# Auth

OK

**Comment by PouryaMansouri** [comment]
# Profile 

### Images

- [x] All Images -> 200
- [x]  get Images -> 200
- [x]  add image -> 201
- [x]  update image -> 200
- [x]  delete image -> 200

**Comment by PouryaMansouri** [comment]
# Profile

### address

- [ ]  list user address -> 200
- [ ] create new user address -> 403 -> CSRF Error @likecodingloveproblems  I did not see this error in API, what should I do?
- [ ] delete user address ->  403 -> CSRF Error @likecodingloveproblems  I did not see this error in API, what should I do?
- [ ] update user address ->  403 -> CSRF Error @likecodingloveproblems  I did not see this error in API, what should I do?
- [ ] retrive user address -> 404

**Comment by PouryaMansouri** [comment]
# Profile 

### Favorite list

- [ ] add to favorite list -> 200
- [ ] remove from -> 204
- [ ]  get my profile -> 200
- [ ]  update mu profile ->200

**Comment by PouryaMansouri** [comment]
#  Profile

### User page

- [x]  get my profile -> 200
- [x]  update mu profile ->200
- [ ] order history list -> 200 not completed #110 
- [ ] order history detail -> 200 not completed #110

**Comment by PouryaMansouri** [comment]
I cant continue , please resolve #110 @likecodingloveproblems

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri I wrote two simple tests in **Auth** now the user only must set 2 environment variables **YOUR_MOBILE** and **YOUR_PASSWORD** and only run requests in respectively.

1. Login/Register Begin Auth
2. Complete Auth
3. Get Access Token

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri 
Landing

404 status:

- [x] /api/v1/landing/amazing-products/ -> deleted
- [x] /api/v1/landing/categories/ -> deleted

500 status:

- [ ] api/v1/landing/most-sold-shops/
- [ ] api/v1/landing/random-shops/

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri first cleanup all 404s, to update our postman with our codebase and check that all Django endpoints have a request in postman

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri list 500s and create an issue for each of them and assign me to them.

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri first cleanup all 404s, to update our postman with our codebase and check that all Django endpoints have a request in postman
 
Are you OK with deleting the 404s? OK.

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri list 500s and create an issue for each of them and assign me to them.

OK

**Comment by likecodingloveproblems** [comment]
It makes us blocked, so i remove it from the flow
