### ISSUE TITLE
پنل جنگو قسمت سفارشات

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#87]
حجره دار قسمت سفارشات تکمیل شده/نشده نمیتواند گزینه ای را بزند که سفارش خود را لغو کند و مشکل خود را بیان کند.همچنین قسمت تایید مشتری نداریم تا حجره دار بزند و سفارش به قسمت تکمیل شده انتقال یابد.قبلا بصورت دستی از طریق فندق انجام میشد اما الان این گزینه هم غیرفعال شده

@PouryaMansouri

**Comment by likecodingloveproblems** [comment]
@MaryamSamareh
 

- [ ] لطفا ی بررسی بکنید ببینید که آیا در داشبورد حجره داری همچین قابلیتی نیست؟
- [ ] کار های بچه ها با پنل ادمین رو هم بررسی کنید ببینید نیاز هاشون چی هست؟ این رو من قبلا هم از بچه ها خواسته بودم.
- [ ] در ضمن پنل ادمین تا اونجایی که یادمه تغییری نداشتیم!

**Comment by MaryamSamareh** [comment]
@PouryaMansouri 
این مورد رو من با بچه های عملیات چک کردم
کاربر نمیتونه رضایت خودش رو توی سایت ثبت کنه و حجره دار هم نمیتونه سفارشی رو لغو کنه. این دوتا کار از سمت عملیات انجام میشن اما در حال حاضر اونا هم دسترسی ندارن.
یعنی وضعیت سفارشات در حالت "در انتظار تایید مشتری" می مونه و نمیشه دیگه تغییرش داد. اما سمت عملیات میخواهند که بتونن وضعیت "در انتظار تسویه با فروشگاه" و "لغو شده" هم داشته باشن (اگه سفارشی لغو بشه، توی وضعیت "در انتظار تایید فروشگاه" میمونه و دیگه تغییری نمیکنه)

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri این مورد رو من با بچه های عملیات چک کردم کاربر نمیتونه رضایت خودش رو توی سایت ثبت کنه و حجره دار هم نمیتونه سفارشی رو لغو کنه. این دوتا کار از سمت عملیات انجام میشن اما در حال حاضر اونا هم دسترسی ندارن. یعنی وضعیت سفارشات در حالت "در انتظار تایید مشتری" می مونه و نمیشه دیگه تغییرش داد. اما سمت عملیات میخواهند که بتونن وضعیت "در انتظار تسویه با فروشگاه" و "لغو شده" هم داشته باشن (اگه سفارشی لغو بشه، توی وضعیت "در انتظار تایید فروشگاه" میمونه و دیگه تغییری نمیکنه)

@likecodingloveproblems 
نظری داری محمد؟

**Comment by likecodingloveproblems** [comment]
I doubt we must put a simple issue to clean up and enhance admin panels so I close this issue.

**Comment by saman7799** [comment]
@likecodingloveproblems 
بعضی از مواردی که در پنل ادمین جنگو توسط تیم عملیات قبلا انجام میشده و الان نمیتوانند انجام بدهند موجب میشه که کارشون پیش نره مواردی که نداشتیم و نیاز به طراحی دارند بحث جدایی هست ولی مواردی که قبلا بوده و الان نمیتوانند انجام بدنند و به خانم شفیعی مراجعه کردند به نظر باید بررسی بشوند

**Comment by likecodingloveproblems** [comment]
> @likecodingloveproblems بعضی از مواردی که در پنل ادمین جنگو توسط تیم عملیات قبلا انجام میشده و الان نمیتوانند انجام بدهند موجب میشه که کارشون پیش نره مواردی که نداشتیم و نیاز به طراحی دارند بحث جدایی هست ولی مواردی که قبلا بوده و الان نمیتوانند انجام بدنند و به خانم شفیعی مراجعه کردند به نظر باید بررسی بشوند

@saman7799 تنها تغییری که خاطرم هست انجام شد این بود که محسن دسترسی تغییر وضعیت فاکتور رو از بچه های  عملیات گرفت و ی دکمه تسویه به پنل اضافه کرد که بچه های مالی بتونن تسویه رو اعلام کنن.
آیا مساله دیگری هم بوده ؟
در ضمن به نظرم نگاهتون رو وسیع تر قرار بدین به شکلی که حتی اضافه کردن ویژگی جدید و مسایلی که احتمال میدیدم که به خاطر دسترسی بچه های عملیات هست رو هم در نظر بگیریم.
ممنون

**Comment by saman7799** [comment]
@likecodingloveproblems 
بله حرف شما درست هست دسترسی دادن زیاد مشکلات ایجاد مکینه
منظور من هم این بود که مواردی که قبلا بوده بررسی بشه و اگر موردی هست برطرف بشه
به نظرم خانم شفیعی چون در ارتباط هستن با تیم عملیات الان میتوانند الان بفرمایند که چه مواردی بوده غیر فعال شده بررسی بشه @sahar-shafiee 
ممنون از همگی

**Comment by saman7799** [comment]
@likecodingloveproblems @sahar-shafiee 
طبق صحبت های انجام شده در جلسه روزانه با آقای مهدوی صحبت شد که این مورد باگ نیست بلکه زمان آقای محسن حسنی دسترسی به مالی داده شده است با این حال گفتند برای بخش مالی هم کار نمیکند حالا باید بررسی شود برای بخش مالی کار میکند یا خیر

**Comment by likecodingloveproblems** [comment]
من  این مساله رو میبندم چون باید در پنل ادمین آورده بشه.
بخش مالی دکمه تسویه شون ارور دسترسی میده که خودم باید بررسیش کنم.
اما ی مورد استفاده برای تیم عملیات وجود داره اونم اینه که وضعیت فاکتور رو مدیریت کنن.

**Comment by saman7799** [comment]
@likecodingloveproblems 
با آقای بنازاده صحبت شد که تیم های عملیات و مالی مواردی رو که از پنل نیاز دارند سند کنند تحویل بدهند تا بررسی شوند.
