### ISSUE TITLE
error api products page

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#94]
https://nakhll.com/api/v1/products/?search=&available=true&page_size=50
@PouryaMansouri

**Comment by milad7212** [comment]
api :
https://nakhll.com/api/v1/products/?search=&available=true&page_size=50
@PouryaMansouri

**Comment by PouryaMansouri** [comment]
> API : https://nakhll.com/api/v1/products/?search=&available=true&page_size=50 @PouryaMansouri

this issue was solved

**Comment by sahar-shafiee** [comment]
@PouryaMansouri 
توسط خانم هاشمی تست شد و این مسئله برطرف شده
