### ISSUE TITLE
ارور درگاه پرداخت

### ISSUE THREAD

**Issue by MaryamSamareh** [nakhll-company/nakhll_backend#97]
متاسفانه درگاه پرداخت اصلا بالا نمی آید

**Comment by sahar-shafiee** [comment]
![Capture](https://user-images.githubusercontent.com/52815608/169641542-d48c5a7b-4a77-47b8-a854-5720029f46f4.JPG)

**Comment by PouryaMansouri** [comment]
مشکل از سمت ما نبوده. درست شد.
