### ISSUE TITLE
صفحات فرود اختصاصی

### ISSUE THREAD

**Issue by sahar-shafiee** [nakhll-company/nakhll_backend#99]
حجره هایی که دارای صفحات فرود اختصاصی بودند به حالت قبل برگشته اند

تیم عملیات در خواست دارد که حجره آن کافی صفحه فرود اختصاصی برایش دوباره فعال شود

برای همه ی حجره ها را دوباره فعال کنیم؟

@PouryaMansouri @likecodingloveproblems

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
you should take this decision.

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri How can this be done?
Is it hardcoded or Operation team can activate this from the admin panel?

**Comment by likecodingloveproblems** [comment]
It does not need a decision as we must give them this option!
the only decision here is to keep our codebase clean :smile:

**Comment by PouryaMansouri** [comment]
> It does not need a decision as we must give them this option! the only decision here is to keep our codebase clean smile

@likecodingloveproblems 
you should give priority level to this issue :))

**Comment by likecodingloveproblems** [comment]
> @PouryaMansouri How can this be done? Is it hardcoded or Operation team can activate this from the admin panel?

@PouryaMansouri what about this?

**Comment by likecodingloveproblems** [comment]
It is prioritized,
what about this 

> @PouryaMansouri How can this be done? Is it hardcoded or Operation team can activate this from the admin panel?

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
if it was just a field that should be changed ( boolean field change to True, we change them in Django panel)

**Comment by sahar-shafiee** [comment]
@PouryaMansouri اقای منصوری بی زحمت صفحه فرود اختصاصی حجره قهوه آن را میشه هرچه سریعتر فعال کنید چون درخواست تیم عملیات هست

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri اقای منصوری بی زحمت صفحه فرود اختصاصی حجره قهوه آن را میشه هرچه سریعتر فعال کنید چون درخواست تیم عملیات هست

حجره قهوه نداریم!!!

**Comment by sahar-shafiee** [comment]
> > @PouryaMansouri اقای منصوری بی زحمت صفحه فرود اختصاصی حجره قهوه آن را میشه هرچه سریعتر فعال کنید چون درخواست تیم عملیات هست
> 
> حجره قهوه نداریم!!!

حجره آن-کافی
@PouryaMansouri

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri please give me a time to discuss it as fast as possible
It's not a good solution to hard code this type of data!

**Comment by PouryaMansouri** [comment]
> @PouryaMansouri please give me a time to discuss it as fast as possible It's not a good solution to hard code this type of data!

OK

**Comment by PouryaMansouri** [comment]
@sahar-shafiee @milad7212 
Please give me the API

**Comment by milad7212** [comment]
/api/v1/shop/{id}/

**Comment by milad7212** [comment]
https://nakhll.com/api/v1/shop/neil-market-food-store/

"is_landing": true,

landing_data: data landing is here
